### ISSUE TITLE
ERROR: Could not build wheels for asyncmy which use PEP 517 and cannot be installed directly 

### ISSUE THREAD

**Issue by landybird** [long2ice/asyncmy#1]
I'm working on platform  `[MSC v.1900 64 bit (AMD64)] on win32`  with `python3.7.7` + `pip 21.0.1`

When I try to install `asyncmy` : 

    pip install asyncmy 

I get errors as below:

```
Collecting asyncmy
  Using cached asyncmy-0.1.3.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: asyncmy
  Building wheel for asyncmy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\virtual\Envs\venv37\Scripts\python.exe' 'D:\virtual\Envs\venv37\lib\s
ite-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\AppData\Local\Temp\tmpy7lkf9p5'
       cwd: C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920
  Complete output (87 lines):
  A setup.py file already exists. Using it.
  Compiling asyncmy\charset.pyx because it changed.
  Compiling asyncmy\connection.pyx because it changed.
  Compiling asyncmy\converters.pyx because it changed.
  Compiling asyncmy\errors.pyx because it changed.
  Compiling asyncmy\protocol.pyx because it changed.
  Compiling asyncmy/constants\__init__.py because it changed.
  [1/6] Cythonizing asyncmy/constants\__init__.py
  [2/6] Cythonizing asyncmy\charset.pyx
  [3/6] Cythonizing asyncmy\connection.pyx
  [4/6] Cythonizing asyncmy\converters.pyx
  [5/6] Cythonizing asyncmy\errors.pyx
  [6/6] Cythonizing asyncmy\protocol.pyx
  running build
  running build_py
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\lib.win-
amd64-3.7
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\lib.win-
amd64-3.7\asyncmy
  copying asyncmy\auth.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f
920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\contexts.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91
af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\cursors.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91a
f0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\optionfile.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f
91af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\pool.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f
920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\version.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91a
f0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\__init__.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91
af0f920\build\lib.win-amd64-3.7\asyncmy
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\lib.win-
amd64-3.7\asyncmy\constants
  copying asyncmy\constants\__init__.py -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9
dac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\charset.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af
0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\charset.pxd -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91
af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\charset.pyx -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91
af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\connection.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f9
1af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\connection.pyx -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09
f91af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\converters.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f9
1af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\converters.pyx -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09
f91af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\errors.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0
f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\errors.pyx -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91a
f0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\protocol.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91a
f0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\protocol.pyx -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f9
1af0f920\build\lib.win-amd64-3.7\asyncmy
  copying asyncmy\constants\CLIENT.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9d
ac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\COMMAND.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9
dac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\CR.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b
09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\ER.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b
09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\FIELD_TYPE.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c3894
4b9dac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\FLAG.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac
2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\SERVER_STATUS.pxi -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c3
8944b9dac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  copying asyncmy\constants\__init__.c -> C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9d
ac2b09f91af0f920\build\lib.win-amd64-3.7\asyncmy\constants
  running build_ext
  building 'asyncmy.charset' extension
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\temp.win
-amd64-3.7
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\temp.win
-amd64-3.7\Release
  creating C:\Users\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\temp.win
-amd64-3.7\Release\asyncmy
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\vi
rtual\Envs\venv37\include -ID:\python37\include -ID:\python37\include "-IC:\Program Files (x86)\Microso
ft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Wi
ndows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcasyncmy\charset.c /FoC:\Users\Dom
ob\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\build\temp.win-amd64-3.7\Release\asyn
cmy\charset.obj
  charset.c
  d:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\constants\__init__.py

    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\charset.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\connection.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\converters.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\errors.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureW
arning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\U
sers\AppData\Local\Temp\pip-install-m3da5atj\asyncmy_f8bb358c38944b9dac2b09f91af0f920\asyncmy\protocol.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit sta
tus 2
  Traceback (most recent call last):
    File "D:\virtual\Envs\venv37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <mo
dule>
      main()
    File "D:\virtual\Envs\venv37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in mai
n
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\virtual\Envs\venv37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 205, in bui
ld_wheel
      metadata_directory)
    File "C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\poetry\core\masonry\api.py",
 line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\poetry\core\masonry\builders
\wheel.py", line 72, in make_in
      wb.build()
    File "C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\poetry\core\masonry\builders
\wheel.py", line 103, in build
      self._build(zip_file)
    File "C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\poetry\core\masonry\builders
\wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "C:\Users\AppData\Local\Temp\pip-build-env-c7oj0ttl\overlay\Lib\site-packages\poetry\core\masonry\builders
\wheel.py", line 169, in _run_build_command
      str(self._path / "build"),
    File "D:\python37\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['D:/virtual/Envs/venv37/Scripts/python.exe', 'C:\\Users\\Dom
ob\\AppData\\Local\\Temp\\pip-install-m3da5atj\\asyncmy_f8bb358c38944b9dac2b09f91af0f920\\setup.py', 'build', '-b', 'C:\\
Users\\AppData\\Local\\Temp\\pip-install-m3da5atj\\asyncmy_f8bb358c38944b9dac2b09f91af0f920\\build']' returned non
-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for asyncmy
Failed to build asyncmy
ERROR: Could not build wheels for asyncmy which use PEP 517 and cannot be installed directly


```

Can you help me to get `asyncmy` installed correctly?

**Comment by long2ice** [comment]
Sorry I don't use Windows and can't test that, I install it Mac and success:
![image](https://user-images.githubusercontent.com/13377178/111274452-f8e23c00-866f-11eb-8ccf-8bfe52a7e536.png)

**Comment by findre** [comment]
centos 20 + python 3.8.10 + pip20.1.2

**Comment by findre** [comment]
我发现 centos:7.2.1511 + python3.8 也安装不了，同样的问题

**Comment by long2ice** [comment]
报错是什么

**Comment by sirkadian** [comment]
I also experience that error, still not found any fix for that

**Comment by thouger** [comment]
我在centos8安装成功,Windows不行..

**Comment by BoilingNine** [comment]
why not support windows
