### ISSUE TITLE
TypeError: object Cursor can't be used in 'await' expression

### ISSUE THREAD

**Issue by R4zzerYT** [long2ice/asyncmy#10]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Yannic\PycharmProjects\YouTube\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Yannic\PycharmProjects\gift-bot\cogs\stats_module.py", line 62, in on_message
    mycursor = await mydb.cursor()
TypeError: object Cursor can't be used in 'await' expression
```

`await mydb.cursor()` is `async` in aiomysql. Why not here?

My code: 
```
mydb = await getConnection()
        mycursor = await mydb.cursor()
        await mycursor.execute("SELECT ignore_role_id, bonus_role_id FROM guild_role_settings WHERE guild_id = %s", (message.author.guild.id,))
        in_database = await mycursor.fetchone()
```

**Comment by long2ice** [comment]
Try latest code

**Comment by long2ice** [comment]
https://github.com/long2ice/asyncmy/releases/tag/v0.1.8

**Comment by coleifer** [comment]
I think this issue is not fixed.
