### ISSUE TITLE
Weird connection error

### ISSUE THREAD

**Issue by jossefaz** [long2ice/asyncmy#28]
Hello,

Thanks for this great library.
I experienced an issue using it with sqlalchemy. It apprently tries to connect using the pool. But it then get a connection error...
Do you have any idea based on this traceback from where this could happens ?
My code worked perfectly with a sync driver (`pymysql`). Once I changed it to `asyncmy`, this connection error occured.

```python
ERROR:Exception in ASGI application
Traceback (most recent call last):
  File "/project/resources/items/repository/variant.py", line 190, in get_variant_by_details_hg38
    result = await self.session.execute(query)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
    return await greenlet_spawn(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3246, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 275, in connect
    await_only(self.asyncmy.connect(*arg, **kw)),
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/project/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "asyncmy/connection.pyx", line 1299, in _connect
  File "asyncmy/connection.pyx", line 555, in connect
  File "asyncmy/connection.pyx", line 532, in asyncmy.connection.Connection.connect
  File "asyncmy/connection.pyx", line 922, in _get_server_information
  File "asyncmy/connection.pyx", line 605, in read_packet
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
  File "asyncmy/errors.pyx", line 134, in asyncmy.errors.raise_mysql_exception
sqlalchemy.exc.OperationalError: (asyncmy.errors.OperationalError) (1040, 'ny connections')
(Background on this error at: https://sqlalche.me/e/14/e3q8)


```

The database is up and I manage to connect to it.

**Comment by long2ice** [comment]
Try add `pool_recycle`

**Comment by jossefaz** [comment]
From the [docs](https://docs.sqlalchemy.org/en/14/core/pooling.html#setting-pool-recycle) : 

> This parameter prevents the pool from using a particular connection that has passed a certain age, and is appropriate for database backends such as MySQL that automatically close connections that have been stale after a particular period of time

So it could be relevent if the connection would happens after a while....but it fails at the very first time.

Anyway, I added the `pool_recycle` and the error still occurs

**Comment by long2ice** [comment]
Show me the code

**Comment by ivankosenko** [comment]
'ny connections' - is truncated message 'Too many connections'.

According to documentation https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html#cs-packet-err-sqlstate-marker in ERR_Packet 5 bytes (sql_state_marker and sql_state) are optional, and it send only when "capabilities & CLIENT_PROTOCOL_41" condition is true. In case 'Too many connections' server don't send [Initial Handshake Packet] and don't receive [Handshake Response Packet]. So server don't know client capabilities, and don't send optional field.

Quick but a bit dirty solution i see like this:
```    
if data[3] == 35: #  symbol '#'
    err_val = data[9:].decode("utf-8", "replace")
else:
    err_val = data[3:].decode("utf-8", "replace")
```
A more reliable solution would probably be to check a flag that remembers if the [Handshake Response Packet] was sent.

**Comment by long2ice** [comment]
What is the `35`?

**Comment by ivankosenko** [comment]
It is ascii code of character '#'.

**Comment by long2ice** [comment]
What about `if data[3] == ord('#')`?

**Comment by ivankosenko** [comment]
Yes, maybe it's better variant. I was just not sure if the function call ord would be optimized by cython, so I wrote the fastest variant. I have no experience with cython yet.

**Comment by ivankosenko** [comment]
I checked. The generated C-code is equivalent to ord(5) and 35. So yes, ord(5) is preferable.
