### ISSUE TITLE
can not install by pdm2.0.0b2

### ISSUE THREAD

**Issue by Redlnn** [long2ice/asyncmy#40]
When I try to install asyncmy by pdm2, I got the following error report.

```py
unearth: Skip link <Link https://files.pythonhosted.org/packages/b4/45/bb26129a0ac8a3694ef9a98d0d47d31e0172ec5778e2b03cd208a12eaff1/asyncmy-0.2.5-cp310-cp310-macosx_10_16_x86_64.whl (from None)>: none of the wheel tags(cp310-cp310-macosx_10_16_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/b6/55/b4d50f7546f55d3ca15679b106e35ad1ae573118fc8337a7f5a2681046ab/asyncmy-0.2.5-cp310-cp310-manylinux_2_31_x86_64.whl (from None)>: none of the wheel tags(cp310-cp310-manylinux_2_31_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/3a/e8/6da7c7a096a74dfdde83602363d8917e9706b131e3895e6b43f9037b31a1/asyncmy-0.2.5-cp37-cp37m-macosx_10_16_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-macosx_10_16_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/8c/91/be0f6c865c3b54413f8620a229a6e1c7bf9944120c956e8a636e5036a488/asyncmy-0.2.5-cp37-cp37m-manylinux_2_31_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-manylinux_2_31_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/7c/04/1cd560e30dd64cda89bee5fe64af19781809e36755289720737e9866b9ae/asyncmy-0.2.5-cp37-cp37m-win_amd64.whl (from None)>: none of the wheel tags(cp37-cp37m-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/9a/b4/77337bb6c1fb7ed8d1a2e6581c76481c43fa8b54205d2790c80983e538ab/asyncmy-0.2.5-cp38-cp38-macosx_10_16_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-macosx_10_16_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/5c/98/4e4ba25000be46a9295964643406142fd1147ca91fd7be4d2824db111b15/asyncmy-0.2.5-cp38-cp38-manylinux_2_31_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-manylinux_2_31_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/f3/47/702fe8952d68ef1363128ef6eca765549b499bd43a1aa0931ef502832450/asyncmy-0.2.5-cp38-cp38-win_amd64.whl (from None)>: none of the wheel tags(cp38-cp38-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/f9/a2/9c46036d77bfbd6f918384f9fc94fcb8d938533918350c7f08311ba7f8c7/asyncmy-0.2.5-cp39-cp39-macosx_10_16_x86_64.whl (from None)>: none of the wheel tags(cp39-cp39-macosx_10_16_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/ec/1c/2bd62723e9ac14825e1e54e6fd76ddfddc72d2a2ecd30c7a050666f5c4da/asyncmy-0.2.5-cp39-cp39-manylinux_2_31_x86_64.whl (from None)>: none of the wheel tags(cp39-cp39-manylinux_2_31_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/c1/46/29abd6dd086fa6dec8bba05cb09ae35dbf65b7dd88c5ea529ca78dae6cf9/asyncmy-0.2.5-cp39-cp39-win_amd64.whl (from None)>: none of the wheel tags(cp39-cp39-win_amd64) are compatible
unearth: Downloading <Link https://files.pythonhosted.org/packages/ca/57/68e75455e84ca789cf2aa8def2bee306c96420f7487a6120c7c6d7ac721e/asyncmy-0.2.5-cp310-cp310-win_amd64.whl (from None)> to C:\Users\user\AppData\Local\Temp\pdm-build-tlr6yrsr\asyncmy-0.2.5-cp310-cp310-win_amd64.whl
  ✖ Install asyncmy 0.2.5 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
    _install_wheel(
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\user\AppData\Local\Temp\pdm-build-tlr6yrsr\asyncmy-0.2.5-cp310-cp310-win_amd64.whl, asyncmy/auth.py is not mentioned in RECORD
Retry failed jobs
  ✖ Install asyncmy 0.2.5 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
    _install_wheel(
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\user\AppData\Local\Temp\pdm-build-tlr6yrsr\asyncmy-0.2.5-cp310-cp310-win_amd64.whl, asyncmy/auth.py is not mentioned in RECORD
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\user\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 256, in main
    return Core().main(args)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 189, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 184, in main
    f(options.project, options)
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\add.py", line 58, in handle
    actions.do_add(
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 288, in do_add
    do_sync(
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 218, in do_sync
    handler.synchronize()
  File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 402, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

**Comment by usrbinsam** [comment]
Same issue

**Comment by long2ice** [comment]
Maybe problem of pdm? Can you install by pip or poetry?

**Comment by Redlnn** [comment]
> Maybe problem of pdm? Can you install by pip or poetry?

yes, I can install by pip and poetry. But I didn't have this problem when installing other packages

**Comment by Redlnn** [comment]
> Maybe problem of pdm? Can you install by pip or poetry?

I found that this problem only occurs in Windows.
I can't reproduce this problem in Ubuntu.
