### ISSUE TITLE
Cannot import asyncmy using python:3.11 in docker 

### ISSUE THREAD

**Issue by yinziyan1206** [long2ice/asyncmy#48]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/asyncmy/__init__.py", line 1, in <module>
    from .connection import Connection, connect  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'asyncmy.connection'

**Comment by vmarkovtsev** [comment]
This must be specific to broken wheels on 3.11. The older Python-s are fine. I see that the difference is that asyncmy builds a wheel vs. downloading prebuilt from pypi, hence my conclusion.

**Comment by dmitrii-begal** [comment]
Just had this error after trying to install `asyncmy` using `pipenv`. I compared `site-packages/asyncmy` directory in virtual env with older virtual env (like a week old). python version, pipenv version, Pipfile.lock are all the same. But I did not find cythonized .pyx
In `asyncmy-0.2.5.dist-info` (old):
```
asyncmy/connection.c,sha256=QSEwZgVW5zN745BLxHlNRRd4Czj2x_KNcJxtJB514YE,2222812
asyncmy/connection.cpython-311-x86_64-linux-gnu.so,sha256=846PORmVOmPVLC6BxI75iGJDatrtMg2mUgzO0XpvRio,4168288
asyncmy/connection.pyx,sha256=9p6JWhJrduHaPYmqdorOjaVePpgIrFQbOtQd5ah81oo,49772
```
In new venv only .pyx is listed.
We did install asyncmy on 3.11 just a week ago and everything worked fine.

WHEEL file is different, though. Old working .venv:
```
...
Generator: poetry-core 1.4.0
...
```
New not-working:
```
...
Generator: poetry-core 1.5.0
...
```

**Comment by yinziyan1206** [comment]
> Just had this error after trying to install `asyncmy` using `pipenv`. I compared `site-packages/asyncmy` directory in virtual env with older virtual env (like a week old). python version, pipenv version, Pipfile.lock are all the same. But I did not find cythonized .pyx In `asyncmy-0.2.5.dist-info` (old):
> 
> ```
> asyncmy/connection.c,sha256=QSEwZgVW5zN745BLxHlNRRd4Czj2x_KNcJxtJB514YE,2222812
> asyncmy/connection.cpython-311-x86_64-linux-gnu.so,sha256=846PORmVOmPVLC6BxI75iGJDatrtMg2mUgzO0XpvRio,4168288
> asyncmy/connection.pyx,sha256=9p6JWhJrduHaPYmqdorOjaVePpgIrFQbOtQd5ah81oo,49772
> ```
> 
> In new venv only .pyx is listed. We did install asyncmy on 3.11 just a week ago and everything worked fine.
> 
> WHEEL file is different, though. Old working .venv:
> 
> ```
> ...
> Generator: poetry-core 1.4.0
> ...
> ```
> 
> New not-working:
> 
> ```
> ...
> Generator: poetry-core 1.5.0
> ...
> ```

So do i. It worked fine several days ago.

**Comment by vmarkovtsev** [comment]
`poetry-core==1.5.0` was released 2 days ago, this makes sense.

**Comment by vmarkovtsev** [comment]
I pinned `poetry-core==1.4.0` but that didn't fix the problem for me, unfortunately.

**Comment by vmarkovtsev** [comment]
Also released in the last few days:
- https://github.com/cpburnz/python-pathspec 0.11.0
- https://github.com/Textualize/rich 13.3.1
- https://github.com/jaraco/zipp 3.12.0

I will try pinning those.

**Comment by dmitrii-begal** [comment]
I managed to build `asyncmy` from source code. Steps:
1. In `pyproject.toml` `[build-system]` section restrict poetry requirement: `requires = ["poetry-core>=1.0.0, <1.5.0", "setuptools", "cython"]`
2. build wheel using poetry `poetry build --format=wheel`
3. install using `pip`: `pip install /path/to/wheel/asyncmy-0.2.6-cp311-cp311-macosx_12_0_arm64.whl`

I suggest to pin `poetry-core` build-system dependency for time being. The method above does not suite my CI process, and I believe other also just want to `pip install asyncmy` or whatever with other dependency manager.

**Comment by giuliano-oliveira** [comment]
This affects python 3.9 as well

**Comment by nkhitrov** [comment]
Hi! It seems a critical error. @long2ice could you update pypi package with fix from #49 ?

**Comment by nkhitrov** [comment]
pipeline failed 😢 

https://github.com/long2ice/asyncmy/actions/runs/4051020319

**Comment by dmitrii-begal** [comment]
@long2ice it seems like PyPi upload action has failed. For now it is only possible to install package from direct link to the repo. Could you please take a look at what went wrong with actions?

**Comment by giuliano-oliveira** [comment]
@dmitrii-begal @long2ice Is this a poetry bug? or is it something specific to asyncmy?

**Comment by jjpaulo2** [comment]
@yinziyan1206 the package works for me at version `0.2.4` on Python 3.11

**Comment by zzzeek** [comment]
I am getting this error right now from just -installed 0.2.6 with Python 3.10

```
$ pip install asyncmy --no-cache
Collecting asyncmy
  Downloading asyncmy-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 13.1 MB/s eta 0:00:00
Installing collected packages: asyncmy
Successfully installed asyncmy-0.2.6

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: pip install --upgrade pip
[classic@photon3 sqlalchemy:main]$ python
Python 3.10.0 (default, Nov  5 2021, 17:23:47) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncmy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/classic/.venv3/lib/python3.10/site-packages/asyncmy/__init__.py", line 1, in <module>
    from .connection import Connection, connect  # noqa:F401
ModuleNotFoundError: No module named 'asyncmy.connection'

```
this is broken. are the bad builds being fixed or what is happening here?
