### ISSUE TITLE
library suddenly not loading on M1 mac

### ISSUE THREAD

**Issue by logi** [long2ice/asyncmy#54]
I don't know if this being on macos and M1 is important, but it seems like it might be.

This minimal test fails consistantly:
```
❯ virtualenv .venv
created virtual environment CPython3.10.3.final.0-64 in 176ms
  creator CPython3Posix(dest=/Users/logi.ragnarsson/asyncmy-test/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/logi.ragnarsson/Library/Application Support/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.7.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```
```
❯ source .venv/bin/activate
```
```
❯ pip install asyncmy==0.2.5
Looking in indexes: https://pypi.org/simple, <redacted>
Collecting asyncmy==0.2.5
  Using cached asyncmy-0.2.5-cp310-cp310-macosx_13_0_arm64.whl
Installing collected packages: asyncmy
Successfully installed asyncmy-0.2.5

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: pip install --upgrade pip
```
```
❯ python3
Python 3.10.3 (main, Mar 27 2022, 13:44:57) [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncmy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/logi.ragnarsson/asyncmy-test/.venv/lib/python3.10/site-packages/asyncmy/__init__.py", line 1, in <module>
    from .connection import Connection, connect  # noqa:F401
ModuleNotFoundError: No module named 'asyncmy.connection'
```

If I install `cython` and then run `pyximport.install()` it _works_, but now we're building the library at startup which is much too slow. Also, using `0.2.7rc6` works immediately.

**Comment by Shoumil** [comment]
Same issue on M2 Mac

**Comment by optsing** [comment]
This problem is reproduced not only on macOS, but also on Windows (python 3.11.2, pip 23.0) and Linux (python 3.8.10, pip 20.0.2)
