### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by NORXND** [long2ice/asyncmy#8]
I run `21.2.4` version of PIP and Python 3.9.5 on `[MSC v.1928 64 bit (AMD64)] on win32`
```
Collecting asyncmy
  Using cached asyncmy-0.1.8.tar.gz (60 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: asyncmy
  Building wheel for asyncmy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\szymo\appdata\local\programs\python\python39\python.exe' 'c:\users\szymo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\szymo\AppData\Local\Temp\tmpbylr_imx'
       cwd: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476
  Complete output (92 lines):
  A setup.py file already exists. Using it.
  C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\asyncmy\charset.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\asyncmy\connection.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\asyncmy\converters.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: asyncmy\converters.pyx:284:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
  C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\asyncmy\errors.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\asyncmy\protocol.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling asyncmy\charset.pyx because it changed.
  Compiling asyncmy\connection.pyx because it changed.
  Compiling asyncmy\converters.pyx because it changed.
  Compiling asyncmy\errors.pyx because it changed.
  Compiling asyncmy\protocol.pyx because it changed.
  [1/5] Cythonizing asyncmy\charset.pyx
  [2/5] Cythonizing asyncmy\connection.pyx
  [3/5] Cythonizing asyncmy\converters.pyx
  [4/5] Cythonizing asyncmy\errors.pyx
  [5/5] Cythonizing asyncmy\protocol.pyx
  c:\users\szymo\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'language_level'
    warnings.warn(msg)
  running build
  running build_py
  creating C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build
  creating C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9
  creating C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\auth.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\contexts.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\cursors.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\optionfile.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\pool.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\version.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\__init__.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  creating C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\CLIENT.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\COLUMN.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\COMMAND.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\CR.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\ER.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\FIELD_TYPE.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\FLAG.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\SERVER_STATUS.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\__init__.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\constants
  creating C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\binlogstream.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\bitmap.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\column.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\constants.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\errors.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\events.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\gtid.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\packets.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\row_events.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\table.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\__init__.py -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\charset.c -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\charset.pxd -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\charset.pyx -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\connection.c -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\connection.pyx -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\converters.c -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\converters.pyx -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\errors.c -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\errors.pyx -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\protocol.c -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\protocol.pyx -> C:\Users\szymo\AppData\Local\Temp\pip-install-g9zcll5k\asyncmy_7a954c26a27641638dc474022ddc7476\build\lib.win-amd64-3.9\asyncmy
  running build_ext
  building 'asyncmy.charset' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Traceback (most recent call last):
    File "c:\users\szymo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "c:\users\szymo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\szymo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 72, in make_in
      wb.build()
    File "C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 103, in build
      self._build(zip_file)
    File "C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "C:\Users\szymo\AppData\Local\Temp\pip-build-env-i62jrr_a\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "c:\users\szymo\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:/users/szymo/appdata/local/programs/python/python39/python.exe', 'C:\\Users\\szymo\\AppData\\Local\\Temp\\pip-install-g9zcll5k\\asyncmy_7a954c26a27641638dc474022ddc7476\\setup.py', 'build', '-b', 'C:\\Users\\szymo\\AppData\\Local\\Temp\\pip-install-g9zcll5k\\asyncmy_7a954c26a27641638dc474022ddc7476\\build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for asyncmy
Failed to build asyncmy
ERROR: Could not build wheels for asyncmy which use PEP 517 and cannot be installed directly
```
Same results with venv and without. I even tried manually downloading .whl but it didn't help.
There was issue about it (#1) but it is closed.

**Comment by long2ice** [comment]
As the error said `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by NORXND** [comment]
@long2ice I have installed it and nothing changed. Am I supposed to do something else after using the installer from the given link?

**Comment by long2ice** [comment]
I'm not sure since I don't use windows, maybe the environment variable, path and so on

**Comment by NORXND** [comment]
I saw the specific error on the internet. Will try to see how it will work out and let you know.

**Comment by NORXND** [comment]
@long2ice Issue solved!
I would recommend to add it to read me:

* Download installer from https://visualstudio.microsoft.com/visual-cpp-build-tools/
* Run `YOUR_DOWNLOADED_INSTALLER.exe --norestart --passive --downloadThenInstall --includeRecommended --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.MSBuildTools`
* Run `pip install asyncmy`

**Comment by long2ice** [comment]
Great! Thanks for share!
