### ISSUE TITLE
pyinstaller package error

### ISSUE THREAD

**Issue by Chise1** [long2ice/asyncmy#93]
When use pyinstaller package asyncmy, will get like this:

```python

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from asyncmy import connect
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "asyncmy\__init__.py", line 1, in <module>
  File "asyncmy\\connection.pyx", line 14, in init asyncmy.connection
ImportError: cannot import name auth
[432] Failed to execute script 'main' due to unhandled exception!


```

use pyinstaller's hiddenimports can fix this problem.

Maybe you can add import in __init__.py,like this:

```python

from asyncmy.connection import Connection, connect  # noqa:F401
from asyncmy.pool import Pool, create_pool  # noqa:F401
from asyncmy import auth
from asyncmy import constants
from asyncmy import structs,converters,charset,optionfile,protocol
from asyncmy import contexts
from asyncmy import version


```

**Comment by CHLOVEN** [comment]
> When use pyinstaller package asyncmy, will get like this:
> 
> ```python
> Traceback (most recent call last):
>   File "main.py", line 11, in <module>
>     from asyncmy import connect
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "asyncmy\__init__.py", line 1, in <module>
>   File "asyncmy\\connection.pyx", line 14, in init asyncmy.connection
> ImportError: cannot import name auth
> [432] Failed to execute script 'main' due to unhandled exception!
> ```
> 
> use pyinstaller's hiddenimports can fix this problem.
> 
> Maybe you can add import in **init**.py,like this:
> 
> ```python
> from asyncmy.connection import Connection, connect  # noqa:F401
> from asyncmy.pool import Pool, create_pool  # noqa:F401
> from asyncmy import auth
> from asyncmy import constants
> from asyncmy import structs,converters,charset,optionfile,protocol
> from asyncmy import contexts
> from asyncmy import version
> ```

Can you provide the command line you using?
Unable to fix this issue by adding `--hidden-import=asyncmy` .

**Comment by Mini-Right** [comment]
![7684e16db83efc340074f6b40f0d571](https://github.com/user-attachments/assets/c0723db5-5689-4515-8a2a-e74128ddfc34)

I encountered the same issue while using PyInstaller for packaging. After resolving it with your code and repackaging, the following error occurred. Now I’m unsure how to proceed with the solution.

**Comment by LaoZhangRen** [comment]
pyinstaller --collect-all asyncmy  --onefile .\run.py
@Mini-Right @Chise1

**Comment by long2ice** [comment]
Answered in-thread: `pyinstaller --collect-all asyncmy` handles this, since the submodules are Cython extensions PyInstaller can't discover statically. Closing as answered.
